[config]
schemaVersion = "0.0.1"

[package]
namespace = "tristanmcpherson"
name = "R2API"
versionNumber = "0.0.1"
description = "A modding API for Risk of Rain 2"
websiteUrl = "https://github.com/risk-of-thunder/R2API"
containsNsfwContent = false

[package.dependencies]
bbepis-BepInExPack = "5.4.9"
RiskofThunder-HookGenPatcher = "1.2.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./ReleaseOutput"
target = "./plugins/R2API"

[publish]
repository = "https://thunderstore.io"
communities = ["riskofrain2"]
categories = ["libraries"]
