
[config]
schemaVersion = "0.0.1"

[package]
namespace = "RiskofThunder"
name = "R2API_ProcType"
versionNumber = "1.0.2"
description = "API for registering proc types"
websiteUrl = "https://github.com/risk-of-thunder/R2API"
containsNsfwContent = false

[package.dependencies]
bbepis-BepInExPack = "5.4.2113"
RiskofThunder-HookGenPatcher = "1.2.3"
RiskofThunder-R2API_Core = "1.0.0"

[build]
icon = "../icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./ReleaseOutput/R2API.ProcType.dll"
target = "./plugins/R2API.ProcType/R2API.ProcType.dll"

[[build.copy]]
source = "./ReleaseOutput/R2API.ProcType.xml"
target = "./plugins/R2API.ProcType/R2API.ProcType.xml"

[[build.copy]]
source = "../R2API.ProcType.Interop/ReleaseOutput/R2API.ProcType.Interop.dll"
target = "./plugins/R2API.ProcType/R2API.ProcType.Interop.dll"

[[build.copy]]
source = "../R2API.ProcType.Patcher/ReleaseOutput/R2API.ProcType.Patcher.dll"
target = "./patchers/R2API.ProcType/R2API.ProcType.Patcher.dll"

[publish]
repository = "https://thunderstore.io"
communities = ["riskofrain2"]
categories = ["libraries"]
