
[config]
schemaVersion = "0.0.1"

[package]
namespace = "RiskofThunder"
name = "R2API_DamageType"
versionNumber = "1.1.5"
description = "API for registering damage types"
websiteUrl = "https://github.com/risk-of-thunder/R2API"
containsNsfwContent = false

[package.dependencies]
bbepis-BepInExPack = "5.4.2109"
RiskofThunder-HookGenPatcher = "1.2.3"
RiskofThunder-R2API_Core = "1.0.0"

[build]
icon = "../icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./ReleaseOutput/R2API.DamageType.dll"
target = "./plugins/R2API.DamageType/R2API.DamageType.dll"

[[build.copy]]
source = "./ReleaseOutput/R2API.DamageType.xml"
target = "./plugins/R2API.DamageType/R2API.DamageType.xml"

[[build.copy]]
source = "../R2API.DamageType.Interop/ReleaseOutput/R2API.DamageType.Interop.dll"
target = "./plugins/R2API.DamageType/R2API.DamageType.Interop.dll"

[[build.copy]]
source = "../R2API.DamageType.Patcher/ReleaseOutput/R2API.DamageType.Patcher.dll"
target = "./patchers/R2API.DamageType/R2API.DamageType.Patcher.dll"

[publish]
repository = "https://thunderstore.io"
communities = ["riskofrain2"]
categories = ["libraries"]
