name: C# API XML Documentation To Github Pages

on: 
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
  
    - name: Build Documentation
      uses: nunit/docfx-action@v3.4.2
      with:
        args: docs/docfx.json

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_site
